name: Labeler

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - name: Label pull requests
        if: github.event_name == 'pull_request'
        run: |
          gh pr edit ${{ github.event.number }} --add-label "needs-review"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Label issues
        if: github.event_name == 'issues'
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "triage"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
